# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_default:
    name: Default arguments
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - name: Check installation
        run: "bash ${GITHUB_WORKSPACE}/install.sh"
        shell: bash

  build_ui:
    name: User-given arguments
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      - name: Check help-string
        run: "bash ${GITHUB_WORKSPACE}/install.sh -h"
        shell: bash

      # Runs a single command using the runners shell
      - name: Check installation
        run: "bash ${GITHUB_WORKSPACE}/install.sh -d ${HOME}/code/dpath -i ${HOME}/code/ipath -c g++ -j 2"
        shell: bash

  build_optional:
    name: Optional libraries
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      # Runs a single command using the runners shell
      - name: Check installation
        run: "bash ${GITHUB_WORKSPACE}/install.sh --optional"
        shell: bash

  build_only_optional:
    name: Only optional libraries
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
          platform: x64

      # Runs a single command using the runners shell
      - name: Check installation
        run: "bash ${GITHUB_WORKSPACE}/install.sh --only-optional"
        shell: bash

  build_h5:
      name: Build with hdf5 support
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
          with:
            fetch-depth: 1

        - name: Setup GCC
          uses: egor-tensin/setup-gcc@v1
          with:
            version: 9
            platform: x64

        - name: Install HDF5
          run: |
            sudo apt update
            sudo apt install --no-install-recommends libhdf5-dev

        - name: Check installation
          run: "bash ${GITHUB_WORKSPACE}/install.sh --only-optional" # HDF5 is optional.
          shell: bash
